version: "3.8"

services:
  user-service:
    build: ./user-service  # Ensure this matches your folder structure
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/userdb
    networks:
      - mynetwork

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"  # Avoid conflict with local MySQL
    networks:
      - mynetwork



  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  product-service:
    build: ./product-service
    container_name: product-service
    restart: always
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProductDB;User Id=sa;Password=YourPassword123!;
    ports:
      - "8001:80"

  product-catalog-service:
    build: ./product-catalog-service
    container_name: product-catalog-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productCatalogDB
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge